### ISSUE TITLE
Use numeric class variables instead of binary classes in defect data set.

### ISSUE THREAD

**Issue by rahlk** [ai-se/Transfer-Learning#33]
Include Config data and compare against Issue #31 and #32

**Comment by rahlk** [comment]
## RESULTS:
```
rank ,         name ,    med   ,  iqr 
----------------------------------------------------
   1 ,          Ivy ,    0.18  ,  0.18 (*              |              ), 0.18,  0.18,  0.37
   2 ,       Lucene ,    0.53  ,  0.21 (            -* |              ), 0.51,  0.53,  0.72
   2 ,          Ant ,    0.57  ,  0.11 (           ----*              ), 0.47,  0.57,  0.58
   2 ,        Jedit ,    0.65  ,  0.05 (               | -*           ), 0.63,  0.65,  0.68
   2 ,          ant ,    0.67  ,  0.40 (    -----------|---*          ), 0.29,  0.67,  0.69
   3 ,        jedit ,    0.68  ,  0.14 (               |  -*          ), 0.66,  0.68,  0.79
   3 ,          Poi ,    0.69  ,  0.12 (               | ---*         ), 0.63,  0.69,  0.75
   3 ,       lucene ,    0.72  ,  0.04 (               |    -*        ), 0.70,  0.72,  0.74
   3 ,          poi ,    0.72  ,  0.18 (               | ----*        ), 0.64,  0.72,  0.82
   4 ,          ivy ,    0.85  ,  0.09 (               |          *   ), 0.85,  0.85,  0.94
```

**Comment by rahlk** [comment]
@timm Thoughts??

**Comment by timm** [comment]
Damn. V.cool

some questions:

+ [] but i thought you were **not** doing continuous classes cause u lost smote? 
+ [] does your data set include continuous AND discrete classes and you smote on the discrete and plan on the continuous (which would be a reasonable approach) btw.
+ [] where are the change graphs? still only moving a small number of attrbites?

**Comment by rahlk** [comment]
@timm 
+ Regarding smote: I realized that smote only take majority/minority classes into account, which means with discrete number of bugs like 0,1,2.... smote undersamples the majority class (0 Bugs) and oversamples the minority classes (all others). This creates a runtime overhead, but results are cool.

+ I haven't thought of the second approach, seems plausible, will give it a shot.

+ Change graphs, on their way. Taking too long.

**Comment by timm** [comment]
take the result and run.do i have this right:

- [ ] while smoting u used two classes false=0 and true>0.
- [ ] while planning you selected the sibling leaf with lowest bugs , and that  "lower than" used the raw numerics

**Comment by rahlk** [comment]
So, I take the training data and SMOTE everything, all classes so there are at least 100 '0' bugs, 50 each of 1,2,3,… bugs. 
For instance, say I had a data set with:
Two hundred instances of '0' bugs, 
Forty instances with '1' bug, 
Twenty instances with '2' bugs, and 
One instance with '3' bugs. 

After I SMOTE the data, it will now have: 
Hundred instances with '0' bugs, 
Fifty instances with '1' bug, 
Fifty instances with '2' bugs, 
Fifty instances with '3' bugs. (Since I had only one instance of 3 bugs, I duplicate that row 50x)

**Comment by rahlk** [comment]
See https://github.com/ai-se/Transfer-Learning/wiki/Week-of-July-20th
