### ISSUE TITLE
Research Arc

### ISSUE THREAD

**Issue by rahlk** [ai-se/transfer-learning#36]
![image](https://cloud.githubusercontent.com/assets/1433964/8534974/ac7d57d2-240f-11e5-93e3-1a1d8fe811a6.png)
### ARC 1
- Argument Env. Recording @ 19:53
- Bring in SMEs (Conceptual structures of Experts). Recording @ 23:13
- Rank them, how good are human experts. Recording @ 23:30
### ARC 2
- Stable Transfers. Recording @ 24:20
- WHERE with different Data Sources
- Synonyms, Cross Company …
- Summary — Recording @ 33:40.

**Comment by timm** [comment]
using lucas's work, you've done "bring in the SMEs"

hmmm... synonyms discovery....

so your milestones are

1) validation
2) transfer learning via relevancy filtering (i.e. cluster)
3) bad smells
4) transfer learning, helped by synonyms?
