### ISSUE TITLE
is it clear the new SMOTE is working?

### ISSUE THREAD

**Issue by timm** [ai-se/Transfer-Learning#38]
i was thinking before we slap ourselves on the back too much re your new method,  was does the RHS of this chart look like with the new SMOTE appraoch?

![screenshot 2015-07-11 11 54 39](https://cloud.githubusercontent.com/assets/29195/8634366/ff709faa-27c3-11e5-8e3c-be926b893277.png)

**Comment by rahlk** [comment]
+ Detects non-defective classes accurately, as the number of defects increases, the prediction accuracy, pd and pf becomes worse. 
```
```
