### ISSUE TITLE
Prediction Accuracy Chart

### ISSUE THREAD

**Issue by rahlk** [ai-se/Transfer-Learning#40]
|         | ant      |      |   |
|---------|----------|------|---|
|         |          |      |   |
| Dataset | Pd       | Pf   |   |
| Tuned   | 0.63     | 0.16 |   |
| Untuned | 0.49     | 0.13 |   |
|         |          |      |   |
|         | camel    |      |   |
|         |          |      |   |
| Dataset | Pd       | Pf   |   |
| Tuned   | 0.56     | 0.37 |   |
| Untuned | 0.49     | 0.31 |   |
|         |          |      |   |
|         | ivy      |      |   |
|         |          |      |   |
| Dataset | Pd       | Pf   |   |
| Tuned   | 0.65     | 0.28 |   |
| Untuned | 0.65     | 0.35 |   |
|         |          |      |   |
|         | jedit    |      |   |
|         |          |      |   |
| Dataset | Pd       | Pf   |   |
| Tuned   | 0.64     | 0.29 |   |
| Untuned | 0.55     | 0.29 |   |
|         |          |      |   |
|         | log4j    |      |   |
|         |          |      |   |
| Dataset | Pd       | Pf   |   |
| Tuned   | 0.30     | 0.06 |   |
| Untuned | 0.32     | 0.06 |   |
|         |          |      |   |
|         | lucene   |      |   |
|         |          |      |   |
| Dataset | Pd       | Pf   |   |
| Tuned   | 0.60     | 0.25 |   |
| Untuned | 0.56     | 0.25 |   |
|         |          |      |   |
|         | poi      |      |   |
|         |          |      |   |
| Dataset | Pd       | Pf   |   |
| Tuned   | 0.60     | 0.10 |   |
| Untuned | 0.56     | 0.31 |   |
|         |          |      |   |
|         | synapse  |      |   |
|         |          |      |   |
| Dataset | Pd       | Pf   |   |
| Tuned   | 0.47     | 0.15 |   |
| Untuned | 0.45     | 0.19 |   |
|         |          |      |   |
|         | velocity |      |   |
|         |          |      |   |
| Dataset | Pd       | Pf   |   |
| Tuned   | 0.76     | 0.60 |   |
| Untuned | 0.78     | 0.60 |   |
|         |          |      |   |
|         | xalan    |      |   |
|         |          |      |   |
| Dataset | Pd       | Pf   |   |
| Tuned   | 0.47     | 0.09 |   |
| Untuned | 0.38     | 0.09 |   |
|         |          |      |   |
|         | xerces   |      |   |
|         |          |      |   |
| Dataset | Pd       | Pf   |   |
| Tuned   | 0.40     | 0.29 |   |
| Untuned | 0.30     | 0.31 |   |

**Comment by timm** [comment]
thanks

i reached out to format it as per table in the paper to reduce my cognitive overload

then i thought.... hang on... there is a grad student who could do that for me...

**Comment by rahlk** [comment]
Yup.. This was just a place holder.

**Comment by timm** [comment]
your false alarms look ungood. even tuned. what does precision look like? it could be argued that that is the metric that matters for assessing output from a simulator

t

**Comment by rahlk** [comment]
Oh hey my bad these are 1-Pf so they're in fact pretty good.

**Comment by timm** [comment]
phew

**Comment by rahlk** [comment]
I compute the specificity, which is 1-Pf. Also, these are averaged over 25
reruns.

**Comment by rahlk** [comment]
``` latex
\begin{figure*}[!t]
\scriptsize
   \begin{center}
   \begin{minipage}{.46\linewidth}
    \begin{tabular}{r@{~}|l@{~}|r@{~}|l@{~}|r@{~}|r@{~}|} \cline{2-6}
   & \multicolumn{5}{c|}{ }\\ 
   
   & \multicolumn{5}{c|}{ Data set  properties}\\ 
   & \multicolumn{5}{c|}{  }\\ 
           & \multicolumn{2}{c|}{training}   & \multicolumn{3}{c|}{testing}      \\ \cline{2-6}
   data set      & versions           & cases & versions     & cases    & \% defective             \\ \hline
        jedit    & 3.2, 4.0, 4.1, 4.2 & 1257      & 4.3          & 492          & 2 \\
        ivy      & 1.1, 1.4           & 352       & 2.0          & 352          & 11 \\
        camel    & 1.0, 1.2, 1.4      & 1819      & 1.6          & 965          & 19 \\
        ant      & 1.3, 1.4, 1.5, 1.6 & 947       & 1.7          & 745          & 22 \\
        synapse  & 1.0, 1.1           & 379       & 1.2          & 256          & 34 \\
        velocity & 1.4, 1.5           & 410       & 1.6          & 229          & 34 \\
        lucene   & 2.0, 2.2           & 442       & 2.4          & 340          & 59 \\
        poi      & 1.5, 2, 2.5        & 936       & 3.0          & 442          & 64 \\
        xerces   & 1.0, 1.2, 1.3      & 1055      & 1.4          & 588          & 74  \\ 
        log4j    & 1.0, 1.1           & 244       & 1.2          & 205          & 92   \\
        xalan    & 2.4, 2.5, 2.6      & 2411      & 2.7          & 909          & 99  \\\hline 
        
        
    \end{tabular}\end{minipage}\begin{minipage}{.4\linewidth}
    \begin{tabular}{|rrr|rrr|rr|l} \cline{1-8}
      \multicolumn{8}{|c|}{  }\\
      \multicolumn{8}{|c|}{  Results from learning}\\
       \multicolumn{8}{|c|}{   }\\
   \multicolumn{3}{|c|}{untuned} & \multicolumn{3}{c|}{tuned} & \multicolumn{2}{c|}{change}\\
  \cline{1-8}
  
  pd & pf & good? & pd & pf & good? & pd & pf\\\cline{1-8}
  73 & 38 & y  & 69 & 36 & y & -4 & -2 & \\
  60 & 14 & y & 69 & 19 & y & 9 & 5 &$\star$\\
  74 & 54 &   & 72 & 50 &   & -2 & -4 \\
  83 & 47 &  & 79 & 31 & y & -4 & -16 & $\star$\\
  63 & 39 & y  & 72 & 38 & y  & 9 & -1 & $\star$\\
  31 & 21 &   & 34 & 14 &   & 3 & -7 \\
  73 & 51 &   & 75 & 43 &  & 2 & -8 \\
  78 & 52 &   & 81 & 39 & y & 3 & -13 & $\star$\\
  63 & 80 &   & 72 & 78 &   & 9 & -2 &$\times$\\
  81 & 58 &   & 80 & 54 &   & 1 & -4 &$\times$\\
  92 & 57 &   & 91 & 54 &   & -1 & -3 &$\times$\\
\hline 
\end{tabular}

\end{minipage}
\end{center}    
  
    \caption{Training and test {\em data set properties} for the Jureczko data sets,
    sorted in ascending order of \% defective examples.
    On the right-hand-side, we show the {\em results from learning}.
    Data is ``good'' if it has recall over 60\% and false alarm under 40\%
(and note that, after tuning, there are more ``good'' than before).
Data   marked with ``$\star$'' show large improvements in performance, after tuning.
Data   marked with ``$\times$'' are ``not good'' since their test suites  have so few non-defective examples (less than 5\% of the total sample) that it becomes harder to find better data towards which we can displace test data.
}\label{fig:j}
\end{figure*}
```

**Comment by rahlk** [comment]
![image](https://cloud.githubusercontent.com/assets/1433964/8964914/3f78937e-35f6-11e5-9513-3fd0ff3f079b.png)

**Comment by timm** [comment]
same pattern as before. 

- no way to work with data with more than 66% defective
- we have five data sets we can use: jedit ivy ant, synapse, poi
- tuning can save poor predictors (3 to 5 are now "good")
- sometimes, tunings gives us larger PDs at the cost of more pf (ivy)
- sometimes it is not effective (jedit)
- other times, its quite benefica:
       +  small pd reductions and large pf reductions: ant: poi
       +  large pd increases with only small changes to pd: e.g. synapse

**Comment by rahlk** [comment]
Agreed

**Comment by rahlk** [comment]
Table updated
