### ISSUE TITLE
Dissimilarity in tuning results

### ISSUE THREAD

**Issue by rahlk** [ai-se/Transfer-Learning#42]

**Comment by timm** [comment]
<em>Hi @timm

I response to your previous email, I went through my code. I noticed that I have done 2 things differently with my DE: 

1.  I keep track of the global best. 
2. I optimize for Precision. 

I am talking to Wei to see how his DE differs from mine. I’ll keep you posted on that. 

For you reference, here’s my implementation of DE https://github.com/ai-se/Transfer-Learning/blob/master/_imports/dEvol.py. (Please see Lines 146 - 177)</em>

ahah! no worries then. you optimize for precision and then  run for pd,pf. that is actually _consistent_ with wei's results... optimizing for pd or pf alone would have achieved high scores on one and terrible scores on the other
